version: "2"

services:
  demoapp:
    build: .
    image: demoapp
    container_name: demoapp
    links: 
      - demodb
    ports:
      - 3000:3000
    volumes: 
      - images:/app/public/images
  demodb:
    build: ./db
    image: demodb
    container_name: demodb
    volumes: 
      - mongodb-data:/data/db:rw

volumes: 
  mongodb-data:
  images: 