version: "2"

services:
  demoapp-auth0:
    build: .
    image: demoapp-auth0
    container_name: demoapp-auth0
    links: 
      - demodb-auth0
    ports:
      - 3000:3000
    volumes: 
      - images-auth0:/app/public/images
  demodb-auth0:
    build: ./db
    image: demodb-auth0
    container_name: demodb-auth0
    volumes: 
      - mongodb-data-auth0:/data/db:rw

volumes: 
  mongodb-data-auth0:
  images-auth0: 